name: sqids
description: Official dart port of Sqids. Generate short YouTube-looking IDs from numbers.
version: 0.0.1
homepage: https://github.com/sqids/sqids-dart

environment:
    sdk: ">=3.2.0 <4.0.0"

dependencies:

dev_dependencies:
    test: ^1.24.9
    lints: ^2.1.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

